name: Update licence

on:
  schedule:
    - cron: "0 7 1 1 *"
  workflow_dispatch:

jobs:
  update-licence:
    uses: FasterSpeeding/Piped/.github/workflows/update-licence.yml@9bfd07889cbe638ef001ac0be22e056e7fef012c
    secrets: inherit
